# Generated by Django 4.0.3 on 2022-04-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mat',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
