# Generated by Django 3.2.9 on 2021-11-17 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_coursepermission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoursePermission',
        ),
    ]
