# Generated by Django 3.2.9 on 2021-11-22 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0045_auto_20211122_2301'),
        ('users', '0004_delete_coursepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, to='courses.CourseRole'),
        ),
    ]
