# Generated by Django 4.0.4 on 2022-06-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0063_delete_participationassessment'),
        ('users', '0004_user_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='users', to='courses.courserole'),
        ),
    ]
