# Generated by Django 4.0.7 on 2022-09-30 12:50

import demo_mode.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_roles'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', demo_mode.models.DemoUserManager()),
            ],
        ),
    ]
