/*
 * Snippets API
 * Test description
 *
 * OpenAPI spec version: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.23
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SnippetsApi);
  }
}(this, function(expect, SnippetsApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('EventTemplateRule', function() {
      beforeEach(function() {
        instance = new SnippetsApi.EventTemplateRule();
      });

      it('should create an instance of EventTemplateRule', function() {
        // TODO: update the code to test EventTemplateRule
        expect(instance).to.be.a(SnippetsApi.EventTemplateRule);
      });

      it('should have the property ruleType (base name: "rule_type")', function() {
        // TODO: update the code to test the property ruleType
        expect(instance).to.have.property('ruleType');
        // expect(instance.ruleType).to.be(expectedValueLiteral);
      });

      it('should have the property targetSlotNumber (base name: "target_slot_number")', function() {
        // TODO: update the code to test the property targetSlotNumber
        expect(instance).to.have.property('targetSlotNumber');
        // expect(instance.targetSlotNumber).to.be(expectedValueLiteral);
      });

      it('should have the property exercises (base name: "exercises")', function() {
        // TODO: update the code to test the property exercises
        expect(instance).to.have.property('exercises');
        // expect(instance.exercises).to.be(expectedValueLiteral);
      });

      it('should have the property clauses (base name: "clauses")', function() {
        // TODO: update the code to test the property clauses
        expect(instance).to.have.property('clauses');
        // expect(instance.clauses).to.be(expectedValueLiteral);
      });

    });
  });

}));
