/*
 * Snippets API
 * Test description
 *
 * OpenAPI spec version: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.23
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SnippetsApi);
  }
}(this, function(expect, SnippetsApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Exercise', function() {
      beforeEach(function() {
        instance = new SnippetsApi.Exercise();
      });

      it('should create an instance of Exercise', function() {
        // TODO: update the code to test Exercise
        expect(instance).to.be.a(SnippetsApi.Exercise);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property text (base name: "text")', function() {
        // TODO: update the code to test the property text
        expect(instance).to.have.property('text');
        // expect(instance.text).to.be(expectedValueLiteral);
      });

      it('should have the property exerciseType (base name: "exercise_type")', function() {
        // TODO: update the code to test the property exerciseType
        expect(instance).to.have.property('exerciseType');
        // expect(instance.exerciseType).to.be(expectedValueLiteral);
      });

      it('should have the property solution (base name: "solution")', function() {
        // TODO: update the code to test the property solution
        expect(instance).to.have.property('solution');
        // expect(instance.solution).to.be(expectedValueLiteral);
      });

      it('should have the property state (base name: "state")', function() {
        // TODO: update the code to test the property state
        expect(instance).to.have.property('state');
        // expect(instance.state).to.be(expectedValueLiteral);
      });

      it('should have the property subExercises (base name: "sub_exercises")', function() {
        // TODO: update the code to test the property subExercises
        expect(instance).to.have.property('subExercises');
        // expect(instance.subExercises).to.be(expectedValueLiteral);
      });

      it('should have the property choices (base name: "choices")', function() {
        // TODO: update the code to test the property choices
        expect(instance).to.have.property('choices');
        // expect(instance.choices).to.be(expectedValueLiteral);
      });

    });
  });

}));
