/*
 * Snippets API
 * Test description
 *
 * OpenAPI spec version: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.23
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/EventTemplateRule'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./EventTemplateRule'));
  } else {
    // Browser globals (root is window)
    if (!root.SnippetsApi) {
      root.SnippetsApi = {};
    }
    root.SnippetsApi.EventTemplate = factory(root.SnippetsApi.ApiClient, root.SnippetsApi.EventTemplateRule);
  }
}(this, function(ApiClient, EventTemplateRule) {
  'use strict';

  /**
   * The EventTemplate model module.
   * @module model/EventTemplate
   * @version v1
   */

  /**
   * Constructs a new <code>EventTemplate</code>.
   * @alias module:model/EventTemplate
   * @class
   * @param rules {Array.<module:model/EventTemplateRule>} 
   */
  var exports = function(rules) {
    this.rules = rules;
  };

  /**
   * Constructs a <code>EventTemplate</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/EventTemplate} obj Optional instance to populate.
   * @return {module:model/EventTemplate} The populated <code>EventTemplate</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('rules'))
        obj.rules = ApiClient.convertToType(data['rules'], [EventTemplateRule]);
    }
    return obj;
  }

  /**
   * @member {String} name
   */
  exports.prototype.name = undefined;

  /**
   * @member {Array.<module:model/EventTemplateRule>} rules
   */
  exports.prototype.rules = undefined;


  return exports;

}));
