/*
 * Snippets API
 * Test description
 *
 * OpenAPI spec version: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.23
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/EventTemplateRuleClause'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./EventTemplateRuleClause'));
  } else {
    // Browser globals (root is window)
    if (!root.SnippetsApi) {
      root.SnippetsApi = {};
    }
    root.SnippetsApi.EventTemplateRule = factory(root.SnippetsApi.ApiClient, root.SnippetsApi.EventTemplateRuleClause);
  }
}(this, function(ApiClient, EventTemplateRuleClause) {
  'use strict';

  /**
   * The EventTemplateRule model module.
   * @module model/EventTemplateRule
   * @version v1
   */

  /**
   * Constructs a new <code>EventTemplateRule</code>.
   * @alias module:model/EventTemplateRule
   * @class
   * @param ruleType {Number} 
   * @param targetSlotNumber {Number} 
   * @param clauses {Array.<module:model/EventTemplateRuleClause>} 
   */
  var exports = function(ruleType, targetSlotNumber, clauses) {
    this.ruleType = ruleType;
    this.targetSlotNumber = targetSlotNumber;
    this.clauses = clauses;
  };

  /**
   * Constructs a <code>EventTemplateRule</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/EventTemplateRule} obj Optional instance to populate.
   * @return {module:model/EventTemplateRule} The populated <code>EventTemplateRule</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('rule_type'))
        obj.ruleType = ApiClient.convertToType(data['rule_type'], 'Number');
      if (data.hasOwnProperty('target_slot_number'))
        obj.targetSlotNumber = ApiClient.convertToType(data['target_slot_number'], 'Number');
      if (data.hasOwnProperty('exercises'))
        obj.exercises = ApiClient.convertToType(data['exercises'], ['Number']);
      if (data.hasOwnProperty('clauses'))
        obj.clauses = ApiClient.convertToType(data['clauses'], [EventTemplateRuleClause]);
    }
    return obj;
  }

  /**
   * @member {Number} ruleType
   */
  exports.prototype.ruleType = undefined;

  /**
   * @member {Number} targetSlotNumber
   */
  exports.prototype.targetSlotNumber = undefined;

  /**
   * @member {Array.<Number>} exercises
   */
  exports.prototype.exercises = undefined;

  /**
   * @member {Array.<module:model/EventTemplateRuleClause>} clauses
   */
  exports.prototype.clauses = undefined;


  return exports;

}));
