/*
 * Snippets API
 * Test description
 *
 * OpenAPI spec version: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.23
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SnippetsApi) {
      root.SnippetsApi = {};
    }
    root.SnippetsApi.EventTemplateRuleClause = factory(root.SnippetsApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The EventTemplateRuleClause model module.
   * @module model/EventTemplateRuleClause
   * @version v1
   */

  /**
   * Constructs a new <code>EventTemplateRuleClause</code>.
   * @alias module:model/EventTemplateRuleClause
   * @class
   * @param tags {Array.<Number>} 
   */
  var exports = function(tags) {
    this.tags = tags;
  };

  /**
   * Constructs a <code>EventTemplateRuleClause</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/EventTemplateRuleClause} obj Optional instance to populate.
   * @return {module:model/EventTemplateRuleClause} The populated <code>EventTemplateRuleClause</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('tags'))
        obj.tags = ApiClient.convertToType(data['tags'], ['Number']);
    }
    return obj;
  }

  /**
   * @member {Array.<Number>} tags
   */
  exports.prototype.tags = undefined;


  return exports;

}));
