/*
 * Snippets API
 * Test description
 *
 * OpenAPI spec version: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.23
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SnippetsApi) {
      root.SnippetsApi = {};
    }
    root.SnippetsApi.Event = factory(root.SnippetsApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The Event model module.
   * @module model/Event
   * @version v1
   */

  /**
   * Constructs a new <code>Event</code>.
   * @alias module:model/Event
   * @class
   * @param name {String} 
   * @param eventType {Number} 
   */
  var exports = function(name, eventType) {
    this.name = name;
    this.eventType = eventType;
  };

  /**
   * Constructs a <code>Event</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Event} obj Optional instance to populate.
   * @return {module:model/Event} The populated <code>Event</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('instructions'))
        obj.instructions = ApiClient.convertToType(data['instructions'], 'String');
      if (data.hasOwnProperty('begin_timestamp'))
        obj.beginTimestamp = ApiClient.convertToType(data['begin_timestamp'], 'Date');
      if (data.hasOwnProperty('end_timestamp'))
        obj.endTimestamp = ApiClient.convertToType(data['end_timestamp'], 'Date');
      if (data.hasOwnProperty('event_type'))
        obj.eventType = ApiClient.convertToType(data['event_type'], 'Number');
      if (data.hasOwnProperty('progression_rule'))
        obj.progressionRule = ApiClient.convertToType(data['progression_rule'], 'Number');
      if (data.hasOwnProperty('state'))
        obj.state = ApiClient.convertToType(data['state'], 'Number');
    }
    return obj;
  }

  /**
   * @member {Number} id
   */
  exports.prototype.id = undefined;

  /**
   * @member {String} name
   */
  exports.prototype.name = undefined;

  /**
   * @member {String} instructions
   */
  exports.prototype.instructions = undefined;

  /**
   * @member {Date} beginTimestamp
   */
  exports.prototype.beginTimestamp = undefined;

  /**
   * @member {Date} endTimestamp
   */
  exports.prototype.endTimestamp = undefined;

  /**
   * @member {Number} eventType
   */
  exports.prototype.eventType = undefined;

  /**
   * @member {Number} progressionRule
   */
  exports.prototype.progressionRule = undefined;

  /**
   * @member {Number} state
   */
  exports.prototype.state = undefined;


  return exports;

}));
