/*
 * Snippets API
 * Test description
 *
 * OpenAPI spec version: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.23
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ExerciseChoice'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ExerciseChoice'));
  } else {
    // Browser globals (root is window)
    if (!root.SnippetsApi) {
      root.SnippetsApi = {};
    }
    root.SnippetsApi.Exercise = factory(root.SnippetsApi.ApiClient, root.SnippetsApi.ExerciseChoice);
  }
}(this, function(ApiClient, ExerciseChoice) {
  'use strict';

  /**
   * The Exercise model module.
   * @module model/Exercise
   * @version v1
   */

  /**
   * Constructs a new <code>Exercise</code>.
   * @alias module:model/Exercise
   * @class
   * @param exerciseType {Number} 
   */
  var exports = function(exerciseType) {
    this.exerciseType = exerciseType;
  };

  /**
   * Constructs a <code>Exercise</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Exercise} obj Optional instance to populate.
   * @return {module:model/Exercise} The populated <code>Exercise</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('text'))
        obj.text = ApiClient.convertToType(data['text'], 'String');
      if (data.hasOwnProperty('exercise_type'))
        obj.exerciseType = ApiClient.convertToType(data['exercise_type'], 'Number');
      if (data.hasOwnProperty('solution'))
        obj.solution = ApiClient.convertToType(data['solution'], 'String');
      if (data.hasOwnProperty('state'))
        obj.state = ApiClient.convertToType(data['state'], 'Number');
      if (data.hasOwnProperty('sub_exercises'))
        obj.subExercises = ApiClient.convertToType(data['sub_exercises'], 'String');
      if (data.hasOwnProperty('choices'))
        obj.choices = ApiClient.convertToType(data['choices'], [ExerciseChoice]);
    }
    return obj;
  }

  /**
   * @member {Number} id
   */
  exports.prototype.id = undefined;

  /**
   * @member {String} text
   */
  exports.prototype.text = undefined;

  /**
   * @member {Number} exerciseType
   */
  exports.prototype.exerciseType = undefined;

  /**
   * @member {String} solution
   */
  exports.prototype.solution = undefined;

  /**
   * @member {Number} state
   */
  exports.prototype.state = undefined;

  /**
   * @member {String} subExercises
   */
  exports.prototype.subExercises = undefined;

  /**
   * @member {Array.<module:model/ExerciseChoice>} choices
   */
  exports.prototype.choices = undefined;


  return exports;

}));
