TURN_IN_PRACTICE_PARTICIPATION = "TURN_IN_PRACTICE_PARTICIPATION"
SUBMIT_EXERCISE_SOLUTION = "SUBMIT_EXERCISE_SOLUTION"
EXERCISE_SOLUTION_APPROVED = "EXERCISE_SOLUTION_APPROVED"

VALID_ACTIONS = {
    TURN_IN_PRACTICE_PARTICIPATION: TURN_IN_PRACTICE_PARTICIPATION,
    SUBMIT_EXERCISE_SOLUTION: SUBMIT_EXERCISE_SOLUTION,
    EXERCISE_SOLUTION_APPROVED: EXERCISE_SOLUTION_APPROVED,
}
