# Generated by Django 3.2.8 on 2021-10-26 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseGradingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_for_correct', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('points_for_blank', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('points_for_incorrect', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('minimum_score_threshold', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('time_to_answer', models.PositiveIntegerField(blank=True, null=True)),
                ('enforce_timeout', models.BooleanField(default=True)),
                ('expected_completion_time', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='eventinstanceslot',
            options={'ordering': ['event_instance_id', 'slot_number']},
        ),
        migrations.AlterModelOptions(
            name='participationassessmentslot',
            options={'ordering': ['assessment_id', 'slot_number']},
        ),
        migrations.AlterModelOptions(
            name='participationsubmissionslot',
            options={'ordering': ['submission_id', 'slot_number']},
        ),
        migrations.RenameField(
            model_name='eventparticipation',
            old_name='current_slot_index',
            new_name='current_slot_number',
        ),
        migrations.RemoveField(
            model_name='eventinstanceslot',
            name='position',
        ),
        migrations.RemoveField(
            model_name='participationassessmentslot',
            name='position',
        ),
        migrations.RemoveField(
            model_name='participationsubmissionslot',
            name='position',
        ),
        migrations.AddField(
            model_name='eventinstanceslot',
            name='slot_number',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participationassessmentslot',
            name='slot_number',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participationsubmissionslot',
            name='slot_number',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='eventinstance',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='eventinstanceslot',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='eventparticipation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='eventtemplate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='eventtemplaterule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='eventtemplateruleclause',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='exercisechoice',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='exercisetestcase',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='participationassessment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='participationassessmentslot',
            name='_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='participationassessmentslot',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='participationsubmission',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='participationsubmissionslot',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddConstraint(
            model_name='eventinstanceslot',
            constraint=models.UniqueConstraint(fields=('event_instance_id', 'slot_number'), name='event_instance_unique_slot_number'),
        ),
        migrations.AddConstraint(
            model_name='participationassessmentslot',
            constraint=models.UniqueConstraint(fields=('assessment_id', 'slot_number'), name='assessment_unique_slot_number'),
        ),
        migrations.AddConstraint(
            model_name='participationsubmissionslot',
            constraint=models.UniqueConstraint(fields=('submission_id', 'slot_number'), name='participation_submission_unique_slot_number'),
        ),
        migrations.AddField(
            model_name='exercisegradingrule',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_grading_rules', to='courses.event'),
        ),
        migrations.AddField(
            model_name='exercisegradingrule',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.exercise'),
        ),
    ]
