# Generated by Django 3.2.8 on 2021-10-28 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20211026_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventparticipation',
            name='assessment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participation', to='courses.participationassessment'),
        ),
        migrations.AlterField(
            model_name='eventparticipation',
            name='submission',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participation', to='courses.participationsubmission'),
        ),
        migrations.AlterField(
            model_name='participationsubmissionslot',
            name='selected_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='courses.exercisechoice'),
        ),
    ]
