# Generated by Django 4.0.1 on 2022-01-16 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_exercisechoice_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.TextField(blank=True),
        ),
    ]
