# Generated by Django 3.2.8 on 2021-10-28 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20211028_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.PositiveIntegerField(choices=[(0, 'Self-service practice'), (1, 'In-class practice'), (2, 'Exam'), (3, 'Assignment'), (4, 'External resource')]),
        ),
    ]
