# Generated by Django 4.0.1 on 2022-01-16 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_event_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='event',
            name='event_unique_name_course',
        ),
    ]
