# Generated by Django 4.0.1 on 2022-01-16 16:02

from django.db import migrations, models
import django.db.models.expressions
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_event_event_unique_name_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created', 'pk']},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['course_id', '-created', 'pk']},
        ),
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['course_id', django.db.models.expressions.OrderBy(django.db.models.expressions.F('parent_id'), nulls_first=True), '-created', django.db.models.expressions.OrderBy(django.db.models.expressions.F('child_position'), nulls_first=True), 'pk']},
        ),
        migrations.AddField(
            model_name='course',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='event',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
