# Generated by Django 3.2.8 on 2021-10-28 16:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0006_auto_20211028_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='limit_access_to',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='state',
            field=models.PositiveIntegerField(choices=[(0, 'Draft'), (1, 'Planned'), (2, 'Open'), (3, 'Closed'), (4, 'Access limited to certain students')]),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='exercise_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Multiple choice, single possible'), (1, 'Multiple choice, multiple possible'), (2, 'Open answer'), (3, 'Completion'), (4, 'Aggregated'), (5, 'JavaScript'), (6, 'Attachment')]),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
