# Generated by Django 4.0.1 on 2022-01-26 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_course_options_alter_event_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='template',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='courses.eventtemplate'),
        ),
    ]
