# Generated by Django 3.2.8 on 2021-10-28 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20211028_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventtemplaterule',
            old_name='slot_number',
            new_name='target_slot_number',
        ),
        migrations.AddField(
            model_name='eventinstanceslot',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_slots', to='courses.eventinstanceslot'),
        ),
        migrations.AddField(
            model_name='participationassessmentslot',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_slots', to='courses.participationassessmentslot'),
        ),
        migrations.AddField(
            model_name='participationsubmissionslot',
            name='attachment',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='participationsubmissionslot',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_slots', to='courses.participationsubmissionslot'),
        ),
    ]
