# Generated by Django 3.2.8 on 2021-10-28 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20211028_2011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventtemplaterule',
            options={'ordering': ['template_id', 'target_slot_number']},
        ),
        migrations.AddConstraint(
            model_name='eventtemplaterule',
            constraint=models.UniqueConstraint(fields=('template_id', 'target_slot_number'), name='template_unique_target_slot_number'),
        ),
    ]
