# Generated by Django 4.0.1 on 2022-01-26 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_event_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='template',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='courses.eventtemplate'),
        ),
    ]
