# Generated by Django 3.2.8 on 2021-10-30 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20211028_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='begin_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
