# Generated by Django 3.2.8 on 2021-10-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20211030_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='progression_rule',
            field=models.PositiveIntegerField(choices=[(0, 'All exercises at once'), (1, 'One at a time, can go back'), (2, 'One at a time, cannot go back')], default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='state',
            field=models.PositiveIntegerField(choices=[(0, 'Draft'), (1, 'Planned'), (2, 'Open'), (3, 'Closed'), (4, 'Access limited to certain students')], default=0),
        ),
    ]
