# Generated by Django 3.2.8 on 2021-10-30 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20211030_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='courses.eventtemplate'),
        ),
    ]
