# Generated by Django 4.0.1 on 2022-02-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_alter_event_template_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='state',
            new_name='_state',
        ),
        migrations.AddField(
            model_name='event',
            name='close_automatically',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='open_automatically',
            field=models.BooleanField(default=True),
        ),
    ]
