# Generated by Django 3.2.8 on 2021-10-30 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_alter_event_template'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventinstanceslot',
            options={'ordering': ['event_instance_id', 'parent', 'slot_number']},
        ),
    ]
