# Generated by Django 4.0.1 on 2022-02-06 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_rename_state_event__state_event_close_automatically_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='_state',
        ),
    ]
