# Generated by Django 3.2.8 on 2021-10-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_eventinstanceslot_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventinstanceslot',
            options={'ordering': ['event_instance_id', 'slot_number']},
        ),
        migrations.RemoveConstraint(
            model_name='eventinstanceslot',
            name='event_instance_unique_slot_number',
        ),
        migrations.AddConstraint(
            model_name='eventinstanceslot',
            constraint=models.UniqueConstraint(fields=('event_instance_id', 'parent', 'slot_number'), name='event_instance_unique_slot_number'),
        ),
    ]
