# Generated by Django 4.0.1 on 2022-02-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_remove_event__state'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='_state',
            field=models.PositiveIntegerField(choices=[(0, 'Draft'), (1, 'Planned'), (2, 'Open'), (3, 'Closed')], default=0),
        ),
    ]
