# Generated by Django 3.2.8 on 2021-10-30 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20211030_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtemplate',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
