# Generated by Django 4.0.1 on 2022-02-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_remove_event__state_event_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='state',
            new_name='_event_state',
        ),
        migrations.RemoveField(
            model_name='course',
            name='enrolled_users',
        ),
        migrations.AlterField(
            model_name='event',
            name='_event_state',
            field=models.PositiveIntegerField(choices=[(0, 'Draft'), (1, 'Planned'), (2, 'Open'), (3, 'Closed')], db_column='state', default=0),
        ),
        migrations.AlterField(
            model_name='eventtemplateruleclause',
            name='tags',
            field=models.ManyToManyField(blank=True, to='courses.Tag'),
        ),
    ]
