# Generated by Django 3.2.8 on 2021-11-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_auto_20211101_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participationsubmissionslot',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
