# Generated by Django 3.2.8 on 2021-11-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_alter_participationsubmissionslot_attachment'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='participationassessmentslot',
            name='assessment_unique_slot_number',
        ),
        migrations.RemoveConstraint(
            model_name='participationsubmissionslot',
            name='participation_submission_unique_slot_number',
        ),
        migrations.AddConstraint(
            model_name='participationassessmentslot',
            constraint=models.UniqueConstraint(fields=('assessment_id', 'parent_id', 'slot_number'), name='assessment_unique_slot_number'),
        ),
        migrations.AddConstraint(
            model_name='participationsubmissionslot',
            constraint=models.UniqueConstraint(fields=('submission_id', 'parent_id', 'slot_number'), name='participation_submission_unique_slot_number'),
        ),
    ]
