# Generated by Django 4.0.1 on 2022-02-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_exercise_private_tags_alter_exercise_public_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtemplaterule',
            name='search_public_tags_only',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
