# Generated by Django 4.0.1 on 2022-02-15 12:54

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_eventtemplaterule_search_public_tags_only'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventtemplaterule',
            options={'ordering': ['template_id', '_ordering']},
        ),
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['course_id', django.db.models.expressions.OrderBy(django.db.models.expressions.F('parent_id'), nulls_first=True), '_ordering', '-created', 'pk']},
        ),
        migrations.AlterModelOptions(
            name='exercisechoice',
            options={'ordering': ['exercise_id', '_ordering']},
        ),
        migrations.RemoveConstraint(
            model_name='eventtemplaterule',
            name='template_unique_target_slot_number',
        ),
        migrations.RemoveConstraint(
            model_name='exercise',
            name='same_parent_unique_child_position',
        ),
        migrations.RemoveField(
            model_name='eventtemplaterule',
            name='target_slot_number',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='child_position',
        ),
        migrations.AddField(
            model_name='eventtemplaterule',
            name='_ordering',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='_ordering',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercisechoice',
            name='_ordering',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
