# Generated by Django 3.2.8 on 2021-11-01 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_auto_20211101_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventparticipation',
            name='assessment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participation', to='courses.participationassessment'),
        ),
        migrations.AlterField(
            model_name='eventparticipation',
            name='submission',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participation', to='courses.participationsubmission'),
        ),
    ]
