# Generated by Django 3.2.8 on 2021-11-02 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_auto_20211101_1526'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['course_id', 'pk']},
        ),
        migrations.AlterModelOptions(
            name='eventinstance',
            options={'ordering': ['event_id', 'pk']},
        ),
        migrations.AlterModelOptions(
            name='eventparticipation',
            options={'ordering': ['begin_timestamp', 'pk']},
        ),
        migrations.AlterModelOptions(
            name='eventtemplate',
            options={'ordering': ['course_id', 'pk']},
        ),
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['course_id', 'pk']},
        ),
        migrations.AlterModelOptions(
            name='exercisechoice',
            options={'ordering': ['exercise_id', 'pk']},
        ),
        migrations.AlterModelOptions(
            name='exercisegradingrule',
            options={'ordering': ['event_id', 'exercise_id']},
        ),
        migrations.AlterModelOptions(
            name='exercisetestcase',
            options={'ordering': ['exercise_id', 'pk']},
        ),
        migrations.AlterModelOptions(
            name='participationassessment',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='participationsubmission',
            options={'ordering': ['pk']},
        ),
        migrations.RemoveConstraint(
            model_name='eventinstanceslot',
            name='event_instance_unique_slot_number',
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('course_id', 'name'), name='event_unique_name_course'),
        ),
        migrations.AddConstraint(
            model_name='eventinstanceslot',
            constraint=models.UniqueConstraint(fields=('event_instance_id', 'parent_id', 'slot_number'), name='event_instance_unique_slot_number'),
        ),
        migrations.AddConstraint(
            model_name='exercisechoice',
            constraint=models.UniqueConstraint(fields=('exercise_id', 'text'), name='same_exercise_unique_choice_text'),
        ),
        migrations.AddConstraint(
            model_name='exercisegradingrule',
            constraint=models.UniqueConstraint(fields=('event_id', 'exercise_id'), name='grading_rule_unique_event_exercise'),
        ),
        migrations.AddConstraint(
            model_name='exercisetestcase',
            constraint=models.UniqueConstraint(fields=('exercise_id', 'code'), name='same_exercise_unique_testcase_code'),
        ),
        migrations.AddConstraint(
            model_name='exercisetestcase',
            constraint=models.UniqueConstraint(fields=('exercise_id', 'label'), name='same_exercise_unique_testcase_label'),
        ),
    ]
