# Generated by Django 3.2.8 on 2021-11-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_auto_20211102_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercisegradingrule',
            name='enforce_timeout',
        ),
        migrations.RemoveField(
            model_name='exercisegradingrule',
            name='expected_completion_time',
        ),
        migrations.RemoveField(
            model_name='exercisegradingrule',
            name='time_to_answer',
        ),
        migrations.AddField(
            model_name='exercisegradingrule',
            name='require_manual_grading',
            field=models.BooleanField(default=False),
        ),
    ]
