# Generated by Django 4.0.1 on 2022-02-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_participationassessment__score'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='exercisechoice',
            constraint=models.UniqueConstraint(fields=('exercise_id', '_ordering'), name='same_exercise_unique_ordering'),
        ),
    ]
