# Generated by Django 4.0.1 on 2022-02-16 13:37

from django.db import migrations, models
import django.db.models.constraints


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_exercisechoice_same_exercise_unique_ordering'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='exercisechoice',
            name='same_exercise_unique_ordering',
        ),
        migrations.AddConstraint(
            model_name='exercisechoice',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('exercise_id', '_ordering'), name='same_exercise_unique_ordering'),
        ),
    ]
