# Generated by Django 3.2.8 on 2021-11-02 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_auto_20211102_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseAssessmentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('require_manual_assessment', models.BooleanField(default=False)),
                ('points_for_correct', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('points_for_blank', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('points_for_incorrect', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('minimum_score_threshold', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_rules', to='courses.event')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.exercise')),
            ],
            options={
                'ordering': ['event_id', 'exercise_id'],
            },
        ),
        migrations.AlterField(
            model_name='participationassessment',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Not assessed'), (1, 'Partially assessed'), (2, 'Fully assessed')], default=0),
        ),
        migrations.DeleteModel(
            name='ExerciseGradingRule',
        ),
        migrations.AddConstraint(
            model_name='exerciseassessmentrule',
            constraint=models.UniqueConstraint(fields=('event_id', 'exercise_id'), name='assessment_rule_unique_event_exercise'),
        ),
    ]
