# Generated by Django 3.2.8 on 2021-11-02 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_auto_20211102_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participationassessment',
            name='state',
        ),
        migrations.AlterField(
            model_name='exerciseassessmentrule',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_rules', to='courses.event'),
        ),
        migrations.AlterField(
            model_name='exerciseassessmentrule',
            name='exercise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.exercise'),
        ),
    ]
