# Generated by Django 4.0.1 on 2022-02-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_eventtemplaterule_same_template_unique_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtemplaterule',
            name='amount',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
