# Generated by Django 3.2.8 on 2021-11-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_auto_20211102_1445'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='exercisechoice',
            name='same_exercise_unique_choice_text',
        ),
        migrations.RemoveConstraint(
            model_name='exercisetestcase',
            name='same_exercise_unique_testcase_label',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.PositiveIntegerField(choices=[(0, 'Self-service practice'), (1, 'In-class practice'), (2, 'Exam'), (3, 'Home assignment'), (4, 'External resource')]),
        ),
    ]
