# Generated by Django 4.0.1 on 2022-02-22 13:17

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_eventtemplaterule_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['course_id', django.db.models.expressions.OrderBy(django.db.models.expressions.F('parent_id'), nulls_first=True), '_ordering', '-modified', 'pk']},
        ),
        migrations.RenameField(
            model_name='participationassessment',
            old_name='state',
            new_name='_assessment_state',
        ),
        migrations.AlterField(
            model_name='participationassessment',
            name='_assessment_state',
            field=models.PositiveIntegerField(choices=[(0, 'Draft'), (1, 'For review'), (2, 'Published')], db_column='state', default=0),
        ),
    ]
