# Generated by Django 3.2.9 on 2021-11-08 00:09

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_auto_20211102_1810'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['course_id', django.db.models.expressions.OrderBy(django.db.models.expressions.F('parent_id'), nulls_first=True), django.db.models.expressions.OrderBy(django.db.models.expressions.F('child_position'), nulls_first=True), 'pk']},
        ),
        migrations.AddField(
            model_name='exercise',
            name='child_position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participationassessment',
            name='visible_to_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eventinstanceslot',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.exercise'),
        ),
        migrations.AlterField(
            model_name='exerciseassessmentrule',
            name='exercise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_rules', to='courses.exercise'),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', False)), fields=('parent_id', 'child_position'), name='same_parent_unique_child_position'),
        ),
    ]
