# Generated by Django 3.2.9 on 2021-11-11 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_auto_20211108_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercisechoice',
            name='correct',
        ),
        migrations.AddField(
            model_name='exercisechoice',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.DeleteModel(
            name='ExerciseAssessmentRule',
        ),
    ]
