# Generated by Django 4.0.1 on 2022-03-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_remove_exercisetestcase_hidden_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercisetestcase',
            old_name='label',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='exercisetestcase',
            name='code',
            field=models.TextField(blank=True),
        ),
    ]
