# Generated by Django 3.2.9 on 2021-11-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_auto_20211111_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='limit_access_to',
        ),
        migrations.AlterField(
            model_name='event',
            name='state',
            field=models.PositiveIntegerField(choices=[(0, 'Draft'), (1, 'Planned'), (2, 'Open'), (3, 'Closed')], default=0),
        ),
        migrations.AlterField(
            model_name='eventtemplaterule',
            name='rule_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Tag-based rule'), (1, 'Exercise ID-based rule'), (2, 'Fully random choice')]),
        ),
    ]
