# Generated by Django 4.0.3 on 2022-03-07 18:06

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0032_participationsubmissionslot_execution_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participationsubmissionslot',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=courses.models.get_attachment_path),
        ),
    ]
