# Generated by Django 4.0.3 on 2022-03-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0033_alter_participationsubmissionslot_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='initial_code',
            field=models.TextField(blank=True),
        ),
    ]
