# Generated by Django 4.0.3 on 2022-03-28 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0034_exercise_initial_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercisechoice',
            old_name='score',
            new_name='score_selected',
        ),
        migrations.AlterField(
            model_name='eventparticipation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participations', to=settings.AUTH_USER_MODEL),
        ),
    ]
