# Generated by Django 3.2.9 on 2021-11-13 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0034_auto_20211113_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participationsubmissionslot',
            name='selected_choice',
        ),
        migrations.AddField(
            model_name='participationsubmissionslot',
            name='selected_choices',
            field=models.ManyToManyField(null=True, to='courses.ExerciseChoice'),
        ),
    ]
