# Generated by Django 3.2.9 on 2021-11-13 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0035_auto_20211113_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participationsubmissionslot',
            name='selected_choices',
            field=models.ManyToManyField(blank=True, to='courses.ExerciseChoice'),
        ),
    ]
