# Generated by Django 4.0.3 on 2022-03-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0035_rename_score_exercisechoice_score_selected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisechoice',
            name='score_unselected',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
