# Generated by Django 3.2.9 on 2021-11-15 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0037_auto_20211114_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePrivilege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privileges', models.JSONField(default='[]')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privileged_users', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privileged_courses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
