# Generated by Django 4.0.3 on 2022-04-01 16:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0038_event_last_lock_update_event_locked_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='awaiting_users',
            field=models.ManyToManyField(blank=True, related_name='awaiting_on_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exercise',
            name='awaiting_users',
            field=models.ManyToManyField(blank=True, related_name='awaiting_on_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
    ]
