# Generated by Django 3.2.9 on 2021-11-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0038_courseprivilege'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseprivilege',
            name='privileges',
            field=models.JSONField(default=list),
        ),
    ]
