# Generated by Django 4.0.3 on 2022-04-02 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0039_event_awaiting_users_exercise_awaiting_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Draft'), (1, 'Private'), (2, 'Public')], default=0),
        ),
    ]
