# Generated by Django 3.2.9 on 2021-11-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0040_event_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Draft'), (1, 'Private'), (2, 'Public')], default=2),
        ),
    ]
