# Generated by Django 4.0.3 on 2022-04-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0040_alter_exercise_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='requires_typescript',
            field=models.BooleanField(default=False),
        ),
    ]
