# Generated by Django 3.2.9 on 2021-11-18 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0041_alter_exercise_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='label',
            field=models.CharField(blank=True, max_length=75),
        ),
    ]
