# Generated by Django 4.0.3 on 2022-04-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0041_exercise_requires_typescript'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='exercise_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Multiple choice, single possible'), (1, 'Multiple choice, multiple possible'), (2, 'Open answer'), (3, 'Completion'), (4, 'Aggregated'), (5, 'JavaScript'), (6, 'Attachment'), (7, 'C')]),
        ),
    ]
