# Generated by Django 4.0.3 on 2022-04-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0042_alter_exercise_exercise_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisetestcase',
            name='expected_stout',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exercisetestcase',
            name='stdin',
            field=models.TextField(blank=True),
        ),
    ]
