# Generated by Django 3.2.9 on 2021-11-22 22:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0042_exercise_label'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoursePrivilege',
            new_name='UserCoursePrivilege',
        ),
    ]
