# Generated by Django 3.2.9 on 2021-11-22 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0043_rename_courseprivilege_usercourseprivilege'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercourseprivilege',
            old_name='privileges',
            new_name='allow_privileges',
        ),
    ]
