# Generated by Django 4.0.3 on 2022-04-06 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0043_exercisetestcase_expected_stout_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercisetestcase',
            old_name='expected_stout',
            new_name='expected_stdout',
        ),
    ]
