# Generated by Django 3.2.9 on 2021-11-22 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0044_rename_privileges_usercourseprivilege_allow_privileges'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('allow_privileges', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['course_id', 'name'],
            },
        ),
        migrations.AddField(
            model_name='usercourseprivilege',
            name='deny_privileges',
            field=models.JSONField(default=list),
        ),
        migrations.AddConstraint(
            model_name='usercourseprivilege',
            constraint=models.UniqueConstraint(fields=('user_id', 'course_id'), name='same_course_unique_user_permission'),
        ),
        migrations.AddField(
            model_name='courserole',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='courses.course'),
        ),
        migrations.AddConstraint(
            model_name='courserole',
            constraint=models.UniqueConstraint(fields=('course_id', 'name'), name='same_course_unique_role_name'),
        ),
    ]
