# Generated by Django 4.0.3 on 2022-04-08 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0044_rename_expected_stout_exercisetestcase_expected_stdout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participationassessment',
            name='_score',
            field=models.TextField(blank=True, null=True),
        ),
    ]
