# Generated by Django 4.0.4 on 2022-04-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0045_alter_participationassessment__score'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventinstanceslot',
            name='_siblings_cache',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participationassessmentslot',
            name='_siblings_cache',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participationsubmissionslot',
            name='_siblings_cache',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
