# Generated by Django 3.2.9 on 2021-11-22 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0045_auto_20211122_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourseprivilege',
            name='deny_privileges',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
