# Generated by Django 3.2.9 on 2021-11-22 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0046_alter_usercourseprivilege_deny_privileges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourseprivilege',
            name='allow_privileges',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
