# Generated by Django 3.2.9 on 2021-11-22 23:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0047_alter_usercourseprivilege_allow_privileges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='progression_rule',
        ),
        migrations.AddField(
            model_name='event',
            name='access_rule',
            field=models.PositiveIntegerField(choices=[(0, 'Allow'), (1, 'Deny')], default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='access_rule_exceptions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='event',
            name='allow_going_back',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='exercises_shown_at_a_time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='users_allowed_past_closure',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
