# Generated by Django 3.2.9 on 2021-11-22 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0048_auto_20211122_2326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventparticipation',
            old_name='current_slot_number',
            new_name='current_slot_cursor',
        ),
    ]
