# Generated by Django 4.0.4 on 2022-04-13 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0048_remove_eventinstanceslot__siblings_cache_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participationassessmentslot',
            name='_submission_sibling',
        ),
        migrations.RemoveField(
            model_name='participationsubmissionslot',
            name='_assessment_sibling',
        ),
    ]
