# Generated by Django 3.2.9 on 2021-11-23 14:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0049_rename_current_slot_number_eventparticipation_current_slot_cursor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='teachers',
        ),
        migrations.RemoveField(
            model_name='participationassessment',
            name='visible_to_student',
        ),
        migrations.AddField(
            model_name='course',
            name='enrolled_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='participationassessment',
            name='state',
            field=models.PositiveIntegerField(choices=[(0, 'Draft'), (1, 'For review'), (2, 'Published')], default=0),
        ),
    ]
