# Generated by Django 4.0.4 on 2022-04-14 23:07

import courses.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0049_remove_participationassessmentslot__submission_sibling_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventparticipation',
            options={'ordering': ['event_id', '-begin_timestamp', 'pk']},
        ),
        migrations.AddField(
            model_name='eventparticipation',
            name='_assessment_state',
            field=models.PositiveIntegerField(choices=[(0, 'Draft'), (1, 'For review'), (2, 'Published')], default=0),
        ),
        migrations.AddField(
            model_name='eventparticipation',
            name='_score',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventparticipation',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='participations', to='courses.event'),
        ),
        migrations.CreateModel(
            name='EventParticipationSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.PositiveIntegerField()),
                ('seen_at', models.DateTimeField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('answer_text', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to=courses.models.get_attachment_path)),
                ('execution_results', models.JSONField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_slots', to='courses.exercise')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_slots', to='courses.eventparticipationslot')),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='courses.eventparticipation')),
                ('selected_choices', models.ManyToManyField(blank=True, to='courses.exercisechoice')),
            ],
            options={
                'ordering': ['participation_id', 'parent_id', 'slot_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='eventparticipationslot',
            constraint=models.UniqueConstraint(fields=('participation_id', 'parent_id', 'slot_number'), name='event_participation_unique_slot_number'),
        ),
    ]
