# Generated by Django 4.0.4 on 2022-04-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0051_alter_eventparticipation_event_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtemplate',
            name='randomize_rule_order',
            field=models.BooleanField(default=False),
        ),
    ]
