# Generated by Django 4.0.4 on 2022-04-24 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0052_eventtemplate_randomize_rule_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventtemplate',
            name='randomize_rule_order',
        ),
        migrations.AddField(
            model_name='event',
            name='randomize_rule_order',
            field=models.BooleanField(default=False),
        ),
    ]
