# Generated by Django 4.0.4 on 2022-05-06 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0053_remove_eventtemplate_randomize_rule_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventtemplateruleclause',
            options={'ordering': ['rule_id', 'id']},
        ),
    ]
