# Generated by Django 4.0.4 on 2022-05-17 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0055_exercise_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventparticipation',
            name='bookmarked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eventparticipation',
            name='assessment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participation', to='courses.participationassessment'),
        ),
        migrations.AlterField(
            model_name='eventparticipation',
            name='submission',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participation', to='courses.participationsubmission'),
        ),
    ]
