# Generated by Django 4.0.4 on 2022-05-26 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0056_eventparticipation_bookmarked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventparticipation',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='eventparticipation',
            name='event_instance',
        ),
        migrations.RemoveField(
            model_name='eventparticipation',
            name='submission',
        ),
    ]
