# Generated by Django 4.0.4 on 2022-05-26 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0057_remove_eventparticipation_assessment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventinstance',
            options={},
        ),
        migrations.RemoveField(
            model_name='eventinstance',
            name='exercises',
        ),
        migrations.DeleteModel(
            name='EventInstanceSlot',
        ),
    ]
