# Generated by Django 4.0.4 on 2022-05-26 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0058_alter_eventinstance_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventInstance',
        ),
    ]
