# Generated by Django 4.0.4 on 2022-05-26 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0060_delete_participationassessmentslot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParticipationSubmissionSlot',
        ),
    ]
