# Generated by Django 4.0.4 on 2022-05-26 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0062_delete_participationsubmission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParticipationAssessment',
        ),
    ]
