# Generated by Django 4.0.5 on 2022-06-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0063_delete_participationassessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='time_limit_exceptions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='event',
            name='time_limit_rule',
            field=models.PositiveSmallIntegerField(choices=[(0, 'No time limit'), (1, 'Time limit')], default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='time_limit_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
