# Generated by Django 4.0.6 on 2022-07-19 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0066_rename_score_selected_exercisechoice_correctness_percentage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercisechoice',
            old_name='correctness_percentage',
            new_name='correctness',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='child_weight',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
