# Generated by Django 4.0.6 on 2022-07-19 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0067_rename_correctness_percentage_exercisechoice_correctness_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventtemplaterule',
            old_name='max_score',
            new_name='weight',
        ),
    ]
