# Generated by Django 4.0.6 on 2022-07-27 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0068_rename_max_score_eventtemplaterule_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('state', models.PositiveSmallIntegerField(choices=[(0, 'Draft'), (1, 'Submitted'), (2, 'Published'), (3, 'Rejected')], default=0)),
                ('_content', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.content')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='courses.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solutions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExerciseSolutionVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('vote_type', models.PositiveSmallIntegerField(choices=[(0, 'Up vote'), (1, 'Down vote')])),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votes', to='courses.exercisesolution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExerciseSolutionComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.content')),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='courses.exercisesolution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
