# Generated by Django 4.0.6 on 2022-07-27 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0069_exercisesolution_exercisesolutionvote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisesolution',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solutions', to=settings.AUTH_USER_MODEL),
        ),
    ]
