# Generated by Django 4.0.6 on 2022-07-29 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0070_alter_exercisesolution_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercisesolutioncomment',
            old_name='content',
            new_name='_content',
        ),
    ]
