# Generated by Django 4.0.6 on 2022-08-07 09:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0071_rename_content_exercisesolutioncomment__content'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisesolution',
            name='bookmarked_by',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_exercise_solutions', to=settings.AUTH_USER_MODEL),
        ),
    ]
