# Generated by Django 4.0.6 on 2022-08-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0072_exercisesolution_bookmarked_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercisesolution',
            options={'ordering': ['exercise_id', 'created']},
        ),
        migrations.AddField(
            model_name='exercise',
            name='all_or_nothing',
            field=models.BooleanField(default=False),
        ),
    ]
