# Generated by Django 4.0.6 on 2022-08-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0073_alter_exercisesolution_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='exercise_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Multiple choice, single possible'), (1, 'Multiple choice, multiple possible'), (2, 'Open answer'), (3, 'Completion'), (4, 'Aggregated'), (5, 'JavaScript'), (6, 'Attachment'), (7, 'C'), (8, 'Python')]),
        ),
    ]
