# Generated by Django 4.0.7 on 2022-09-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0074_alter_exercise_exercise_type'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='eventparticipation',
            constraint=models.UniqueConstraint(fields=('event_id', 'user_id'), name='event_participation_unique_user'),
        ),
    ]
