# Generated by Django 4.0.7 on 2022-09-10 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0075_eventparticipation_event_participation_unique_user'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='eventparticipationslot',
            constraint=models.UniqueConstraint(condition=models.Q(('parent_id', None)), fields=('participation_id', 'slot_number'), name='event_participation_unique_base_slot_number'),
        ),
    ]
