# Generated by Django 4.0.7 on 2022-11-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0077_exercisetestcaseattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='last_heartbeat',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='last_heartbeat',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
