# Generated by Django 4.0.8 on 2023-02-07 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_avatar_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0080_course_bookmarked_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('enrollment_type', models.PositiveSmallIntegerField(choices=[(0, 'Default'), (1, 'Automatic'), (2, 'By Teacher')], default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='course',
            name='enrolled_users',
            field=models.ManyToManyField(related_name='enrolled_courses', through='courses.UserCourseEnrollment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usercourseenrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course'),
        ),
        migrations.AddField(
            model_name='usercourseenrollment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL),
        ),
    ]
