# Generated by Django 4.0.9 on 2023-02-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0081_usercourseenrollment_course_enrolled_users_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='usercourseenrollment',
            constraint=models.UniqueConstraint(fields=('user_id', 'course_id'), name='same_course_unique_enrollment'),
        ),
    ]
