# Generated by Django 4.0.10 on 2023-03-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0083_alter_eventparticipation_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventparticipation',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'In progress'), (1, 'Turned in'), (2, 'Closed by teacher')], default=0),
        ),
    ]
