# Generated by Django 3.2.20 on 2023-11-29 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0081_pretotypedata'),
        ('courses', '0084_alter_eventparticipation_state'),
    ]

    operations = [
    ]
