# Generated by Django 3.2.20 on 2023-11-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0085_merge_20231129_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='_features',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
