# Generated by Django 3.2.20 on 2023-11-30 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0086_course__features'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='visibility',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Private'), (1, 'Public')], default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='access_rule',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Allow'), (1, 'Deny')], default=0),
        ),
    ]
