# Generated by Django 3.2.20 on 2023-11-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0087_auto_20231130_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='visibility',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Unlisted'), (1, 'Public')], default=0),
        ),
    ]
