# Generated by Django 3.2.20 on 2023-12-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0089_event_retriability'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='show_assessment_rule',
            field=models.PositiveSmallIntegerField(choices=[(0, 'After publishing'), (1, 'Immediately')], default=0),
        ),
    ]
