# Generated by Django 3.2.8 on 2021-10-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_alter_tag_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Difficulty'), (1, 'Topic'), (2, 'Event-specific'), (3, 'Generic')], default=1),
        ),
    ]
