# Generated by Django 4.0.7 on 2022-09-28 21:37

import demo_mode.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemoInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_invitee_email', models.CharField(max_length=250, validators=[django.core.validators.EmailValidator()])),
                ('other_invitees_emails', models.JSONField(default=list, validators=[demo_mode.models.validate_list_of_emails])),
                ('state', models.PositiveSmallIntegerField(choices=[(0, 'Active'), (1, 'Expired'), (2, 'Pending'), (3, 'Revoked')], default=2)),
                ('duration_hours', models.PositiveIntegerField(default=168)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
