# Generated by Django 4.0.7 on 2022-09-30 12:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_mode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demoinvitation',
            name='main_invitee_email',
            field=models.CharField(max_length=250, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
