# Generated by Django 4.0.8 on 2022-11-28 07:52

import course_tree.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_tree', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filenode',
            old_name='file',
            new_name='_file',
        ),
        migrations.AddField(
            model_name='filenode',
            name='mime_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='filenode',
            name='_file',
            field=models.FileField(blank=True, db_column='file', null=True, upload_to=course_tree.models.get_filenode_file_path),
        ),
    ]
