# Generated by Django 4.0.8 on 2022-11-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_tree', '0002_rename_file_filenode__file_filenode_mime_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filenode',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
