# Generated by Django 4.0.8 on 2022-12-02 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_tree', '0004_alter_filenode_thumbnail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basecoursetreenode',
            options={'ordering': ('tree_id', '-lft')},
        ),
    ]
