# Generated by Django 4.0.8 on 2022-12-02 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course_tree', '0005_alter_basecoursetreenode_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basecoursetreenode',
            options={'base_manager_name': 'objects', 'ordering': ('tree_id', 'lft')},
        ),
        migrations.CreateModel(
            name='NodeComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('comment', models.CharField(max_length=500)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='course_tree.basecoursetreenode')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('node_id', 'created'),
            },
        ),
    ]
