# Generated by Django 4.0.8 on 2022-12-05 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_tree', '0006_alter_basecoursetreenode_options_nodecomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementNode',
            fields=[
                ('basecoursetreenode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='course_tree.basecoursetreenode')),
                ('body', models.TextField(blank=True)),
                ('state', models.PositiveSmallIntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
            ],
            options={
                'ordering': ('tree_id', 'lft'),
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('course_tree.basecoursetreenode',),
        ),
    ]
