# Generated by Django 4.0.8 on 2022-12-06 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0007_alter_user_managers'),
        ('course_tree', '0007_announcementnode'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollNode',
            fields=[
                ('basecoursetreenode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='course_tree.basecoursetreenode')),
                ('text', models.TextField(blank=True)),
                ('state', models.PositiveSmallIntegerField(choices=[(0, 'Draft'), (1, 'Open'), (2, 'Closed')], default=0)),
            ],
            options={
                'ordering': ('tree_id', 'lft'),
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('course_tree.basecoursetreenode',),
        ),
        migrations.CreateModel(
            name='PollNodeChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='PollNodeChoiceSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('poll_node_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_tree.pollnodechoice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='pollnodechoice',
            name='selections',
            field=models.ManyToManyField(related_name='selected_by', through='course_tree.PollNodeChoiceSelection', to=settings.AUTH_USER_MODEL),
        ),
    ]
