# Generated by Django 4.0.8 on 2023-01-01 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_tree', '0008_pollnode_pollnodechoice_pollnodeparticipation'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pollnodeparticipation',
            constraint=models.UniqueConstraint(fields=('poll_id', 'user_id'), name='poll_participation_unique_user'),
        ),
    ]
