# Generated by Django 4.0.10 on 2023-03-29 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_tree', '0009_pollnodeparticipation_poll_participation_unique_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcementnode',
            options={},
        ),
        migrations.AlterModelOptions(
            name='lessonnode',
            options={},
        ),
        migrations.AddField(
            model_name='announcementnode',
            name='schedule_publish_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonnode',
            name='schedule_publish_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
