# Generated by Django 4.0.10 on 2023-03-06 09:14

import core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleOAuth2Credentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', encrypted_model_fields.fields.EncryptedTextField()),
                ('refresh_token', encrypted_model_fields.fields.EncryptedTextField()),
                ('id_token', encrypted_model_fields.fields.EncryptedTextField()),
                ('scope', models.JSONField(validators=[core.validators.validate_str_list])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
