# Generated by Django 4.0.10 on 2023-03-06 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='googleoauth2credentials',
            options={'verbose_name': 'GoogleOAuth2Credentials', 'verbose_name_plural': 'GoogleOAuth2Credentials'},
        ),
    ]
