# Generated by Django 4.0.10 on 2023-03-06 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('integrations', '0002_alter_googleoauth2credentials_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googleoauth2credentials',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
