# Generated by Django 4.0.6 on 2022-07-27 13:47

import content.models
from django.db import migrations, models
import hashid_field.field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, prefix='', primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('text_content', models.TextField(blank=True)),
                ('file_content', models.FileField(blank=True, null=True, upload_to=content.models.Content.get_attachment_path)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
