# Generated by Django 4.1 on 2022-08-24 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gamification", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="goallevel",
            name="requirements",
        ),
        migrations.CreateModel(
            name="GoalLevelActionDefinitionRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.PositiveIntegerField()),
                (
                    "action_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gamification.actiondefinition",
                    ),
                ),
                (
                    "goal_level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gamification.goallevel",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="goallevel",
            name="requirements",
            field=models.ManyToManyField(
                through="gamification.GoalLevelActionDefinitionRequirement",
                to="gamification.actiondefinition",
            ),
        ),
    ]
