# Generated by Django 4.1 on 2022-08-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamification", "0002_remove_goallevel_requirements_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actiondefinition",
            name="parameters",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
