# Generated by Django 4.1 on 2022-08-25 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "gamification",
            "0004_remove_actiondefinition_parameters_goalprogress_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="actiondefinition",
            old_name="points_awarded",
            new_name="reputation_awarded",
        ),
        migrations.RenameField(
            model_name="goallevel",
            old_name="points_awarded",
            new_name="reputation_awarded",
        ),
    ]
