# Generated by Django 4.1 on 2022-08-25 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "gamification",
            "0005_rename_points_awarded_actiondefinition_reputation_awarded_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="actiondefinition",
            name="context",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="action_definitions",
                to="gamification.gamificationcontext",
            ),
        ),
    ]
