# Generated by Django 4.1 on 2022-08-25 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gamification", "0006_alter_actiondefinition_context"),
    ]

    operations = [
        migrations.RenameField(
            model_name="actiondefinition",
            old_name="action",
            new_name="action_code",
        ),
    ]
