# Generated by Django 4.0.10 on 2023-03-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleclassroomcoursetwin',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
