# Generated by Django 4.0.10 on 2023-03-20 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_tree', '0009_pollnodeparticipation_poll_participation_unique_user'),
        ('classroom', '0004_googleclassroomcourseworktwin'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleClassroomMaterialTwin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_object_id', models.TextField()),
                ('data', models.JSONField(default=dict)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='course_tree.lessonnode')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GoogleClassroomAnnouncementTwin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_object_id', models.TextField()),
                ('data', models.JSONField(default=dict)),
                ('announcement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='course_tree.announcementnode')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
