# Generated by Django 4.0.10 on 2023-03-21 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0082_usercourseenrollment_same_course_unique_enrollment'),
        ('classroom', '0005_googleclassroommaterialtwin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleClassroomEnrollmentTwin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_object_id', models.TextField()),
                ('data', models.JSONField(default=dict)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.usercourseenrollment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
