# Generated by Django 4.0.10 on 2023-04-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0007_googleclassroomcourseworksubmissiontwin'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleClassroomIntegrationFailedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255)),
                ('error_kind', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
